### ISSUE TITLE
pasar archivos a raíz

### ISSUE THREAD

**Issue by ixicale** [duvangithub/flask_contacts_app#2]
para evitar tener un fichero de este estilo 
```
/
    carpeta_app/
        app.py
```

es mejor solo tener en raiz todo lo que tienes en carpeta_app, es una buena practica para que tengas separado por micro servicio cada repo ( si fuera el caso que hagas mucho mas exhaustivo un sistema)

**Comment by duvandevs** [comment]
Puse los archivos en la raíz del repositorio
