### ISSUE TITLE
tipo de dato esperado en tus endpoints

### ISSUE THREAD

**Issue by ixicale** [duvangithub/flask_contacts_app#3]
Veo que tienes algunos con tipos de datos definidos y otros no para tu CRUD, lo ideal es que hagas explicito el tipo de dato que esperas para que tengas mejor lectura y sintaxis dentro de tu codogi, es una buena practica. 

### CHIDO:

https://github.com/duvangithub/flask_contacts_app/blob/main/flask_contacts_app/App.py#L68

### NO chido

https://github.com/duvangithub/flask_contacts_app/blob/main/flask_contacts_app/App.py#L41

https://github.com/duvangithub/flask_contacts_app/blob/main/flask_contacts_app/App.py#L49

**Comment by duvandevs** [comment]
Agregue los tipos de datos en los endpoint
