### ISSUE TITLE
tipos de datos de entrada desde endpoints

### ISSUE THREAD

**Issue by ixicale** [duvangithub/flask_contacts_app#4]
Algunas funciones no especificas el tipo de servicio que es, aunque pueda ser entendible a simple vista, es mucho mejor si le indicas al servicio que espera ser algun tipo de request (GET, POST, PUT, PATCH, DELETE, etc)

solo es cuestion de cambiar el decorador que define el endpoint 

```python
tu_endpoint_url:str = "/edit/<string:id>" # ------------- solo es un ejemplo, no necesario definir con variables

@app.route(tu_endpoint_url) # ------------- incompleto
def get_algo();
    pass
@app.route(tu_endpoint_url, method=["GET"]) # ------------- mas chido
def get_algo();
    pass
```

**Comment by duvandevs** [comment]
Se agregaron los tipos de entrada a los endpoint
