### ISSUE TITLE
validacion innecesaria

### ISSUE THREAD

**Issue by ixicale** [duvangithub/flask_contacts_app#5]
Tienes un if que valida el tipo de metodo del servicio, pero siempre será un `True`, por lo tanto no es necesario que se aplique la condicion

https://github.com/duvangithub/flask_contacts_app/blob/main/flask_contacts_app/App.py#L30

> PD1: Si por alguna razon llegara a ser `False`, el servicio va a tronar por que no tiene un return "de cajon" (fuera del if)

https://github.com/duvangithub/flask_contacts_app/blob/main/flask_contacts_app/App.py#L65

> PD2: APLICA EN TODOS LOS METODOS POST

**Comment by duvandevs** [comment]
Quite la validación de más
